---
kind: pipeline
name: default
type: docker

steps:
  - name: postgres
    image: postgres:10.1-alpine
    detach: true 
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
  
  - name: cassandra
    image: cassandra:3.11
    detach: true 
    environment:
      CASSANDRA_CLUSTER_NAME: kong
      CASSANDRA_DC: DC1
      CASSANDRA_RACK: RACK1
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
  
  - name: wait postgres
    image: postgres:10.1-alpine
    commands:
      - until 
          psql -h postgres -U kong -d kong  -c "select 1"; 
        do 
          sleep 1; 
        done

  - name: wait cassandra
    image: cassandra:3.11
    commands:
      - until cqlsh cassandra; do sleep 1; done
  
  - name: migrate
    image: kong:2.1.4-alpine
    environment:
      KONG_PG_HOST: postgres
      KONG_PG_DATABASE: kong
      KONG_CASSANDRA_CONTACT_POINTS: cassandra
      KONG_CASSANDRA_DATA_CENTERS: DC1:1
      KONG_CASSANDRA_REPL_STRATEGY: NetworkTopologyStrategy
      KONG_CASSANDRA_LOCAL_DATACENTER: DC1
    commands: 
      - KONG_DATABASE=postgres kong migrations bootstrap
      - KONG_DATABASE=cassandra kong migrations bootstrap
    
  - name: test
    image: rucciva/kong-dev-onbuild:2.1.4
    pull: "always"
    environment:
      SPEC_KONG_PG_HOST: postgres
      SPEC_KONG_PG_DATABASE: kong
      SPEC_KONG_CASSANDRA_CONTACT_POINTS: cassandra
      SPEC_KONG_CASSANDRA_DATA_CENTERS: DC1:1
      SPEC_KONG_CASSANDRA_REPL_STRATEGY: NetworkTopologyStrategy
      SPEC_KONG_CASSANDRA_LOCAL_DATACENTER: DC1
      SPEC_KONG_LOG_LEVEL: info
      SPEC_KONG_DNS_RESOLVER: " "
      SPEC_KONG_PROXY_ACCESS_LOG: /proc/1/fd/1
      SPEC_KONG_PROXY_ERROR_LOG: /proc/1/fd/2
      SPEC_KONG_ADMIN_ACCESS_LOG: /proc/1/fd/1
      SPEC_KONG_ADMIN_ERROR_LOG: /proc/1/fd/2
    commands:
      - /entrypoint.sh
      - ln -s $$DRONE_WORKSPACE/kong/plugins/myplugin /usr/local/src/kong/kong/plugins/myplugin
      - ln -s $$DRONE_WORKSPACE/spec/myplugin /usr/local/src/kong/spec/myplugin
      - luarocks make
      - cd /usr/local/src/kong/ && bin/busted -v spec/myplugin

  - name: publish rock
    image: rucciva/kong-dev-onbuild:2.1.4
    environment:
      LUAROCKS_API_KEY:
          from_secret: LUAROCKS_API_KEY
    commands: 
      - luarocks upload *.rockspec --api-key="$LUAROCKS_API_KEY"
    when:
      event: 
        - tag
