version: "3.4"
services:
  postgres:
    image: postgres:10.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=kong
      - POSTGRES_USER=kong
    networks:
      kong_dev_net:
        ipv4_address: 172.16.1.2
  migrator:
    image: kong:0.13.0-alpine
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=postgres
      - KONG_PG_DATABASE=kong
    command: "kong migrations up"
    networks:
      kong_dev_net:
        ipv4_address: 172.16.1.3
  kong:
    build: .
    image: rucciva/kong-plugin-dev
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=postgres
      - MOBDEBUG_SERVER=docker.for.mac.localhost
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_TRUSTED_IPS=0.0.0.0/0,::/0
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
    volumes:
      - ./volumes/kong/usr/local/share/lua/5.1:/usr/local/share/lua/5.1
      - ./volumes/kong/prefix:/prefix
    networks:
      kong_dev_net:
        ipv4_address: 172.16.1.4
  kong_busted:
    build: .
    image: rucciva/kong-plugin-dev
    environment:
      - SPEC_KONG_DATABASE=postgres
      - SPEC_KONG_PG_HOST=172.16.1.2
      - SPEC_KONG_PG_DATABASE=kong
      - SPEC_KONG_LOG_LEVEL=debug
      - SPEC_KONG_DNS_RESOLVER=8.8.8.8
      - SPEC_KONG_PROXY_ACCESS_LOG=/proc/1/fd/1
      - SPEC_KONG_PROXY_ERROR_LOG=/proc/1/fd/2
      - SPEC_KONG_ADMIN_ACCESS_LOG=/proc/1/fd/2
      - SPEC_KONG_ADMIN_ERROR_LOG=/proc/1/fd/2
    volumes:
      - ./kong/plugins/myplugin:/usr/local/src/kong/kong/plugins/myplugin
      - ./spec/myplugin:/usr/local/src/kong/spec/myplugin
    working_dir: /usr/local/src/kong/
    command: bin/busted -v spec/myplugin
    networks:
      kong_dev_net:
        ipv4_address: 172.16.1.5
networks:
  kong_dev_net:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.16.1.0/24